### ISSUE TITLE
请问这个运行出错具体是哪方面出现问题了？

### ISSUE THREAD

**Issue by kimanlo** [KCCat/dnspod-httpdns-proxy#2]
Linux自带python2，后来安装了python3，并默认使用2.7，调用3.6。

### 用Python2方式
运行 python httpdns.py，在43行有错误，具体错误如下：
```
  File "httpdns.py", line 43
    return len(Rdata), b''.join([b'\xc0\x0c\x00\x01\x00\x01',self.TTL, b'\x00\x04']).join([Qdata, *Rdata]), Rdata_tmp
                                                                                                  ^
SyntaxError: invalid syntax
```
### 用Python3方式
运行 python3 httpdns.py，具体错误如下：
```
^CTraceback (most recent call last):
  File "httpdns.py", line 137, in <module>
    Rcode, Qdata=localserver.input()
  File "httpdns.py", line 100, in input
    data, self.addr=self.udpfd.recvfrom(1500)
KeyboardInterrupt
```

**请问这个运行出错具体是哪方面出现问题了？**

**Comment by KCCat** [comment]
没有看错的话，python3运行的时候是输入了键盘中断。  
然后程序本身应该是没有任何提示的，只有python自己的错误提示。

**Comment by kimanlo** [comment]
对的，假若我不键盘中断，程序都无法运行呢。。。。。。
就是静止在那里。。。。

**Comment by KCCat** [comment]
如果你是用`ip-prefix`分支的话，你要修改`httpdns.py`里的IP段来适应你的网络。  
默认填的是中国移动的IP段，DNS查询A记录不是IP段里的IP的话，是不会返回结果的。  
如果你要返回所有查询得到的A记录，你可以用主分支的版本。

然后，因为程序本身没有任何提示，所以要检测是否工作正常，  
你可以在设置好`httpdns.py`里需要绑定的地址和端口后用`nslookup`之类的命令测试，  
如果端口不是标准的53端口可以用`dig`等可以自定义查询端口的工具来测试。

**Comment by kimanlo** [comment]
谢谢您的详细解答~我再去尝试！

**Comment by ghost** [comment]
@KCCat 不兼容linux？ 试了一下，只有windows能跑起来，master分支版本，报同样的错误。

**Comment by ghost** [comment]
@KCCat 没学过py，谷歌到 https://stackoverflow.com/questions/3870778/why-does-this-cause-a-syntax-error ，应该是 [Qdata, *Rdata] 的问题。

**Comment by ghost** [comment]
@KCCat  更换python3.4 到 python3.6之后 运行正常

**Comment by KCCat** [comment]
@suikatomoki 啊不好意思,没有仔细测试过版本兼容性,当时是在3.5上写的.
